### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by parro-it** [parro-it/libui-node#42]
I plan to follow this roadmap to implement new features and improvement, please comment:
# Beta 1 - 0.1.0
- [ ] - Complete documentation - UiArea 
- [ ] - Complete documentation - UiGrid
- [ ] - Complete documentation - Menus 
- [ ] - Memory managament
# Beta 2 - 0.2.0
- [ ] - Implement UiTable
- [ ] - Implement various enums
- [ ] - Bump nbind to 0.3.0: nullable arguments, enhanced type checking, fixed callbacks arguments
# Beta 3 - 0.3.0
- [ ] - Precompile binaries with node-pregyp and publish them to github
- [ ] - Application packager - probably in its own repo

**Comment by parro-it** [comment]
Two year later, this is completely exceeded by reality, so I close it.
